## Preprocessing

In [24]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [25]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [26]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [27]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [28]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 100
application_types_to_replace = application_df["APPLICATION_TYPE"].value_counts()[application_df["APPLICATION_TYPE"].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [29]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [30]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts >1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [31]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_replace = 10

# create list of classifications with the cutoff_replace value
classifications_to_replace = list(classification_counts[classification_counts <= cutoff_replace].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
Other      118
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
Name: count, dtype: int64

In [32]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df = application_df.astype(int)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [33]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=["IS_SUCCESSFUL"])
y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
hidden_nodes_1 = 100
hidden_nodes_2 = 100

input_features = len(X_train_scaled[0])

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(hidden_nodes_1, activation="relu", input_shape=(input_features,)))

# Second hidden layer
nn.add(tf.keras.layers.Dense(hidden_nodes_2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 100)               6700

 dense_7 (Dense)             (None, 100)               10100

 dense_8 (Dense)             (None, 1)                 101

=================================================================
Total params: 16901 (66.02 KB)
Trainable params: 16901 (66.02 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
# Compile the model
nn.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [42]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, verbose=2)

Epoch 1/100
858/858 - 1s - loss: 0.5342 - accuracy: 0.7402 - 1s/epoch - 2ms/step
Epoch 2/100
858/858 - 2s - loss: 0.5338 - accuracy: 0.7395 - 2s/epoch - 3ms/step
Epoch 3/100
858/858 - 2s - loss: 0.5337 - accuracy: 0.7404 - 2s/epoch - 2ms/step
Epoch 4/100
858/858 - 1s - loss: 0.5334 - accuracy: 0.7406 - 1s/epoch - 2ms/step
Epoch 5/100
858/858 - 2s - loss: 0.5335 - accuracy: 0.7406 - 2s/epoch - 2ms/step
Epoch 6/100
858/858 - 2s - loss: 0.5332 - accuracy: 0.7420 - 2s/epoch - 2ms/step
Epoch 7/100
858/858 - 2s - loss: 0.5329 - accuracy: 0.7411 - 2s/epoch - 2ms/step
Epoch 8/100
858/858 - 2s - loss: 0.5324 - accuracy: 0.7413 - 2s/epoch - 2ms/step
Epoch 9/100
858/858 - 2s - loss: 0.5329 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 10/100
858/858 - 2s - loss: 0.5322 - accuracy: 0.7408 - 2s/epoch - 3ms/step
Epoch 11/100
858/858 - 2s - loss: 0.5326 - accuracy: 0.7407 - 2s/epoch - 2ms/step
Epoch 12/100
858/858 - 2s - loss: 0.5322 - accuracy: 0.7416 - 2s/epoch - 2ms/step
Epoch 13/100
858/858 - 2s - loss: 0.5315 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 14/100
858/858 - 2s - loss: 0.5321 - accuracy: 0.7413 - 2s/epoch - 2ms/step
Epoch 15/100
858/858 - 2s - loss: 0.5314 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 16/100
858/858 - 2s - loss: 0.5312 - accuracy: 0.7425 - 2s/epoch - 2ms/step
Epoch 17/100
858/858 - 2s - loss: 0.5317 - accuracy: 0.7416 - 2s/epoch - 2ms/step
Epoch 18/100
858/858 - 3s - loss: 0.5313 - accuracy: 0.7411 - 3s/epoch - 3ms/step
Epoch 19/100
858/858 - 2s - loss: 0.5308 - accuracy: 0.7410 - 2s/epoch - 2ms/step
Epoch 20/100
858/858 - 2s - loss: 0.5308 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 21/100
858/858 - 2s - loss: 0.5311 - accuracy: 0.7418 - 2s/epoch - 2ms/step
Epoch 22/100
858/858 - 2s - loss: 0.5307 - accuracy: 0.7424 - 2s/epoch - 2ms/step
Epoch 23/100
858/858 - 2s - loss: 0.5304 - accuracy: 0.7421 - 2s/epoch - 3ms/step
Epoch 24/100
858/858 - 3s - loss: 0.5303 - accuracy: 0.7412 - 3s/epoch - 3ms/step
Epoch 25/100
858/858 - 2s - loss: 0.5306 - accuracy: 0.7422 - 2s/epoch - 2ms/step
Epoch 26/100
858/858 - 2s - loss: 0.5304 - accuracy: 0.7416 - 2s/epoch - 2ms/step
Epoch 27/100
858/858 - 2s - loss: 0.5305 - accuracy: 0.7422 - 2s/epoch - 2ms/step
Epoch 28/100
858/858 - 2s - loss: 0.5301 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 29/100
858/858 - 2s - loss: 0.5301 - accuracy: 0.7422 - 2s/epoch - 2ms/step
Epoch 30/100
858/858 - 2s - loss: 0.5293 - accuracy: 0.7424 - 2s/epoch - 3ms/step
Epoch 31/100
858/858 - 3s - loss: 0.5302 - accuracy: 0.7418 - 3s/epoch - 3ms/step
Epoch 32/100
858/858 - 2s - loss: 0.5300 - accuracy: 0.7422 - 2s/epoch - 2ms/step
Epoch 33/100
858/858 - 2s - loss: 0.5306 - accuracy: 0.7410 - 2s/epoch - 2ms/step
Epoch 34/100
858/858 - 2s - loss: 0.5298 - accuracy: 0.7428 - 2s/epoch - 2ms/step
Epoch 35/100
858/858 - 2s - loss: 0.5290 - accuracy: 0.7419 - 2s/epoch - 2ms/step
Epoch 36/100
858/858 - 2s - loss: 0.5298 - accuracy: 0.7411 - 2s/epoch - 2ms/step
Epoch 37/100
858/858 - 2s - loss: 0.5294 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 38/100
858/858 - 2s - loss: 0.5292 - accuracy: 0.7420 - 2s/epoch - 3ms/step
Epoch 39/100
858/858 - 3s - loss: 0.5295 - accuracy: 0.7420 - 3s/epoch - 3ms/step
Epoch 40/100
858/858 - 3s - loss: 0.5290 - accuracy: 0.7426 - 3s/epoch - 3ms/step
Epoch 41/100
858/858 - 2s - loss: 0.5293 - accuracy: 0.7422 - 2s/epoch - 2ms/step
Epoch 42/100
858/858 - 2s - loss: 0.5293 - accuracy: 0.7425 - 2s/epoch - 2ms/step
Epoch 43/100
858/858 - 2s - loss: 0.5284 - accuracy: 0.7428 - 2s/epoch - 2ms/step
Epoch 44/100
858/858 - 2s - loss: 0.5293 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 45/100
858/858 - 2s - loss: 0.5293 - accuracy: 0.7421 - 2s/epoch - 2ms/step
Epoch 46/100
858/858 - 2s - loss: 0.5284 - accuracy: 0.7424 - 2s/epoch - 3ms/step
Epoch 47/100
858/858 - 2s - loss: 0.5280 - accuracy: 0.7425 - 2s/epoch - 2ms/step
Epoch 48/100
858/858 - 2s - loss: 0.5286 - accuracy: 0.7424 - 2s/epoch - 2ms/step
Epoch 49/100
858/858 - 2s - loss: 0.5284 - accuracy: 0.7421 - 2s/epoch - 2ms/step
Epoch 50/100
858/858 - 2s - loss: 0.5281 - accuracy: 0.7429 - 2s/epoch - 2ms/step
Epoch 51/100
858/858 - 2s - loss: 0.5286 - accuracy: 0.7428 - 2s/epoch - 2ms/step
Epoch 52/100
858/858 - 1s - loss: 0.5284 - accuracy: 0.7430 - 1s/epoch - 2ms/step
Epoch 53/100
858/858 - 2s - loss: 0.5291 - accuracy: 0.7422 - 2s/epoch - 2ms/step
Epoch 54/100
858/858 - 3s - loss: 0.5279 - accuracy: 0.7435 - 3s/epoch - 3ms/step
Epoch 55/100
858/858 - 2s - loss: 0.5280 - accuracy: 0.7426 - 2s/epoch - 2ms/step
Epoch 56/100
858/858 - 2s - loss: 0.5288 - accuracy: 0.7423 - 2s/epoch - 2ms/step
Epoch 57/100
858/858 - 1s - loss: 0.5277 - accuracy: 0.7420 - 1s/epoch - 2ms/step
Epoch 58/100
858/858 - 2s - loss: 0.5284 - accuracy: 0.7438 - 2s/epoch - 2ms/step
Epoch 59/100
858/858 - 2s - loss: 0.5284 - accuracy: 0.7429 - 2s/epoch - 2ms/step
Epoch 60/100
858/858 - 2s - loss: 0.5283 - accuracy: 0.7424 - 2s/epoch - 2ms/step
Epoch 61/100
858/858 - 2s - loss: 0.5278 - accuracy: 0.7428 - 2s/epoch - 2ms/step
Epoch 62/100
858/858 - 3s - loss: 0.5276 - accuracy: 0.7426 - 3s/epoch - 3ms/step
Epoch 63/100
858/858 - 1s - loss: 0.5273 - accuracy: 0.7433 - 1s/epoch - 2ms/step
Epoch 64/100
858/858 - 1s - loss: 0.5275 - accuracy: 0.7432 - 1s/epoch - 2ms/step
Epoch 65/100
858/858 - 1s - loss: 0.5278 - accuracy: 0.7435 - 1s/epoch - 2ms/step
Epoch 66/100
858/858 - 2s - loss: 0.5273 - accuracy: 0.7423 - 2s/epoch - 2ms/step
Epoch 67/100
858/858 - 2s - loss: 0.5274 - accuracy: 0.7423 - 2s/epoch - 2ms/step
Epoch 68/100
858/858 - 2s - loss: 0.5278 - accuracy: 0.7427 - 2s/epoch - 2ms/step
Epoch 69/100
858/858 - 2s - loss: 0.5286 - accuracy: 0.7427 - 2s/epoch - 2ms/step
Epoch 70/100
858/858 - 2s - loss: 0.5281 - accuracy: 0.7434 - 2s/epoch - 3ms/step
Epoch 71/100
858/858 - 2s - loss: 0.5281 - accuracy: 0.7431 - 2s/epoch - 2ms/step
Epoch 72/100
858/858 - 2s - loss: 0.5272 - accuracy: 0.7435 - 2s/epoch - 2ms/step
Epoch 73/100
858/858 - 2s - loss: 0.5268 - accuracy: 0.7434 - 2s/epoch - 2ms/step
Epoch 74/100
858/858 - 2s - loss: 0.5273 - accuracy: 0.7428 - 2s/epoch - 2ms/step
Epoch 75/100
858/858 - 2s - loss: 0.5269 - accuracy: 0.7432 - 2s/epoch - 2ms/step
Epoch 76/100
858/858 - 2s - loss: 0.5277 - accuracy: 0.7440 - 2s/epoch - 2ms/step
Epoch 77/100
858/858 - 2s - loss: 0.5282 - accuracy: 0.7432 - 2s/epoch - 2ms/step
Epoch 78/100
858/858 - 3s - loss: 0.5279 - accuracy: 0.7432 - 3s/epoch - 4ms/step
Epoch 79/100
858/858 - 2s - loss: 0.5272 - accuracy: 0.7438 - 2s/epoch - 2ms/step
Epoch 80/100
858/858 - 2s - loss: 0.5270 - accuracy: 0.7436 - 2s/epoch - 2ms/step
Epoch 81/100
858/858 - 2s - loss: 0.5283 - accuracy: 0.7436 - 2s/epoch - 2ms/step
Epoch 82/100
858/858 - 2s - loss: 0.5268 - accuracy: 0.7433 - 2s/epoch - 2ms/step
Epoch 83/100
858/858 - 2s - loss: 0.5268 - accuracy: 0.7435 - 2s/epoch - 2ms/step
Epoch 84/100
858/858 - 2s - loss: 0.5270 - accuracy: 0.7427 - 2s/epoch - 2ms/step
Epoch 85/100
858/858 - 2s - loss: 0.5268 - accuracy: 0.7436 - 2s/epoch - 3ms/step
Epoch 86/100
858/858 - 2s - loss: 0.5268 - accuracy: 0.7433 - 2s/epoch - 2ms/step
Epoch 87/100
858/858 - 2s - loss: 0.5271 - accuracy: 0.7428 - 2s/epoch - 2ms/step
Epoch 88/100
858/858 - 2s - loss: 0.5265 - accuracy: 0.7439 - 2s/epoch - 2ms/step
Epoch 89/100
858/858 - 2s - loss: 0.5276 - accuracy: 0.7434 - 2s/epoch - 2ms/step
Epoch 90/100
858/858 - 2s - loss: 0.5265 - accuracy: 0.7440 - 2s/epoch - 2ms/step
Epoch 91/100
858/858 - 2s - loss: 0.5274 - accuracy: 0.7445 - 2s/epoch - 2ms/step
Epoch 92/100
858/858 - 2s - loss: 0.5280 - accuracy: 0.7430 - 2s/epoch - 2ms/step
Epoch 93/100
858/858 - 2s - loss: 0.5275 - accuracy: 0.7427 - 2s/epoch - 3ms/step
Epoch 94/100
858/858 - 2s - loss: 0.5273 - accuracy: 0.7436 - 2s/epoch - 2ms/step
Epoch 95/100
858/858 - 2s - loss: 0.5259 - accuracy: 0.7436 - 2s/epoch - 2ms/step
Epoch 96/100
858/858 - 2s - loss: 0.5266 - accuracy: 0.7431 - 2s/epoch - 2ms/step
Epoch 97/100
858/858 - 2s - loss: 0.5293 - accuracy: 0.7434 - 2s/epoch - 2ms/step
Epoch 98/100
858/858 - 1s - loss: 0.5263 - accuracy: 0.7439 - 1s/epoch - 2ms/step
Epoch 99/100
858/858 - 1s - loss: 0.5267 - accuracy: 0.7444 - 1s/epoch - 2ms/step
Epoch 100/100
858/858 - 1s - loss: 0.5268 - accuracy: 0.7435 - 1s/epoch - 2ms/step

In [43]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.6292 - accuracy: 0.7280 - 451ms/epoch - 2ms/step
Loss: 0.629200279712677, Accuracy: 0.7279883623123169

In [44]:
# Export our model to HDF5 file
nn.save("model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(